### ISSUE TITLE
[Discussion] 원리가 궁금합니다.

### ISSUE THREAD

**Issue by youngmin-gwon** [pjs102793/PyRustBoost#1]
# Descriptions
- `python` 을 `rust` 로 대체한다는 것이 무슨 의미인가요? 어떻게 동작하는지 머릿속에 잘 그려지지 않는데 설명해줄 수 있나요?

**Comment by pjs102793** [comment]
최근에 여러 Python 라이브러리가 성능적인 제한 때문에 핵심 부분을 Rust로 대체하는 작업이 몇몇 보여서 재미용으로 하나 레포를 파봤습니다 ㅋ.ㅋ

예를 들어 Pylint를 Rust로 대체하여 만든 [ruff](https://github.com/charliermarsh/ruff)라든지 등등 pydantic 라이브러리의 [core](https://github.com/pydantic/pydantic-core)를 Rust로 대체하는 경우도 있었구요.

Python 라이브러리를 교체하는데에는 [PyO3](https://github.com/PyO3/pyo3)의 프로젝트이 공이 큰거 같습니다. 이 라이브러리를 통해서 Rust 함수를 작성하면 python에서 라이브러리로 불러올수 있는 기능도 제공을 하더라구요.
[링크](https://github.com/PyO3/pyo3#examples) 클릭하시면 이 라이브러리를 통해서 개발된 Example 등을 볼 수 있습니다. 각 Example들을 보시면 하나같이 다 엄청난 성능 향상을 볼 수 있구요.

그래서 PyO3 리파지토리에 저장되어 있는 [이 아티클](https://ohadravid.github.io/posts/2023-03-rusty-python/)을 통해서 한번 튜토리얼을 해보려고 합니다. 이 아티클을 작업을 따라해보면서 이 리파지토리에 반영 할 것 같습니다.

**Comment by youngmin-gwon** [comment]
음 그렇군요. 그럼 원리가 이게 맞나요?

> rust 로 라이브러리 혹은 모듈을 작성한 이후, pyo3 를 이용하여 파이썬에서 사용할 수 있도록 python API를 노출하고, 이를 rust API 와 binding 시킨다. 

흥미롭습니다.

**Comment by pjs102793** [comment]
> 음 그렇군요. 그럼 원리가 이게 맞나요?
> 
> > rust 로 라이브러리 혹은 모듈을 작성한 이후, pyo3 를 이용하여 파이썬에서 사용할 수 있도록 python API를 노출하고, 이를 rust API 와 binding 시킨다.
> 
> 흥미롭습니다.

맞습니다 👍
